import os
import pandas as pd
import glob
import matplotlib.pyplot as plt

# Read all CSV files generated by Spark
base_dir = os.path.expanduser("~/aggregated_telemetry")
files = glob.glob(os.path.join(base_dir, "*.csv"))
df = pd.concat([pd.read_csv(f) for f in files], ignore_index=True)

# Convert timestamps to datetime
df['start_time'] = pd.to_datetime(df['start_time'])

# Plot average height
plt.figure(figsize=(10, 5))
plt.plot(df['start_time'], df['avg_height'], marker='o')
plt.title("Average Drone Height per 10-Second Window")
plt.xlabel("Time")
plt.ylabel("Height (cm)")
plt.grid(True)
plt.tight_layout()
plt.show()

# Plot average battery
plt.figure(figsize=(10, 5))
plt.plot(df['start_time'], df['avg_battery'], marker='o')
plt.title("Average Drone Battery per 10-Second Window")
plt.xlabel("Time")
plt.ylabel("Battery (%)")
plt.grid(True)
plt.tight_layout()
plt.show()

# Plot average pitch
plt.figure(figsize=(10, 5))
plt.plot(df['start_time'], df['avg_pitch'], marker='o')
plt.title("Average Drone Pitch per 10-Second Window")
plt.xlabel("Time")
plt.ylabel("Pitch (deg)")
plt.grid(True)
plt.tight_layout()
plt.show()

# Plot average roll
plt.figure(figsize=(10, 5))
plt.plot(df['start_time'], df['avg_roll'], marker='o')
plt.title("Average Drone Roll per 10-Second Window")
plt.xlabel("Time")
plt.ylabel("Roll (deg)")
plt.grid(True)
plt.tight_layout()
plt.show()

# Plot average yaw
plt.figure(figsize=(10, 5))
plt.plot(df['start_time'], df['avg_yaw'], marker='o')
plt.title("Average Drone Yaw per 10-Second Window")
plt.xlabel("Time")
plt.ylabel("Yaw (deg)")
plt.grid(True)
plt.tight_layout()
plt.show()